version: '3'
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=1234
  redis:
    image: "redis:latest"
  api:
    image: lenesi/fibonaci-server
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_DATABASE=postgres
      - PG_PASSWORD=1234
      - PG_PORT=5432
  client:
    image: lenesi/fibonaci-client
  worker:
    image: lenesi/fibonaci-worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  web:
    restart: always
    image: lenesi/fibonaci-nginx
    ports:
      - '80:80'
    depends_on:
      - api
      - client