name: Deploy Frontend
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build -t lenesi/fibonaci-client-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true lenesi/fibonaci-client-test npm run test
      # Cretae production containers images
      - run: docker build -t lenesi/fibonaci-client ./client
      - run: docker build -t lenesi/fibonaci-nginx ./nginx
      - run: docker build -t lenesi/fibonaci-server ./server
      - run: docker build -t lenesi/fibonaci-worker ./worker
      # publish images to docker hub
      - run: docker push lenesi/fibonaci-client
      - run: docker push lenesi/fibonaci-nginx
      - run: docker push lenesi/fibonaci-server
      - run: docker push lenesi/fibonaci-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: Fibonaci
          environment_name: Fibonaci-env
          region: eu-west-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
